spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/lagou?characterEncoding=utf-8
    password: root
    username: root
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-file-size: 10MB
mybatis:
  type-aliases-package: com.lg.dzf.pojo